In [1]:
import numpy as np

In [2]:
# cast a list into array
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [3]:
#cast 2d array from nested list
my_list = [[1,2,3],[4,5,6]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6]])

## using inbuilt function to create array much faster

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2) #stepsize 2

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,3)) #dimention of array should be passed as toouple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#to create equally seperated n number between a and b
np.linspace(0,10,20)#vector of 20 number equly seperated between o and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.linspace(0,10,5 )#vector of 5 number equly seperated between o and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
# Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# create array of random numbers
np.random.rand(5)

array([0.64723774, 0.01023259, 0.88830408, 0.36670577, 0.46397578])

In [19]:
np.random.rand(5,4)

array([[0.91416025, 0.33182222, 0.57769516, 0.17844379],
       [0.27678398, 0.48646547, 0.8163228 , 0.70599767],
       [0.824308  , 0.70724914, 0.38235126, 0.55930944],
       [0.2458596 , 0.92725363, 0.13521574, 0.58882456],
       [0.53332857, 0.50124804, 0.0175155 , 0.85754443]])

In [24]:
np.random.randint(1,100,5) #generate 5 random int between 1 to 100

array([88, 50, 67, 70,  8])

In [26]:
arr =np.random.randint(1,100,50)
arr

array([96, 32, 70, 70, 78,  5, 19, 89, 38, 21, 20, 56, 93, 49, 89, 28, 62,
       78, 56, 17, 52, 90, 73, 34, 36, 42,  1, 12, 61, 36, 54, 99, 62, 25,
       77, 28, 27, 50, 73, 87, 59,  5, 61, 28, 98, 66, 28, 25, 80, 97])

In [27]:
arr2 = arr >50 
arr2

array([ True, False,  True,  True,  True, False, False,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True,  True,  True, False, False, False, False,
       False,  True, False,  True,  True,  True, False,  True, False,
       False, False,  True,  True,  True, False,  True, False,  True,
        True, False, False,  True,  True])

In [28]:
#now filter all data less than 50
arr[arr2]

array([96, 70, 70, 78, 89, 56, 93, 89, 62, 78, 56, 52, 90, 73, 61, 54, 99,
       62, 77, 73, 87, 59, 61, 98, 66, 80, 97])

In [29]:
#sortcut
arr[arr>50]

array([96, 70, 70, 78, 89, 56, 93, 89, 62, 78, 56, 52, 90, 73, 61, 54, 99,
       62, 77, 73, 87, 59, 61, 98, 66, 80, 97])

# Reshape

In [30]:
len(arr)

50

In [31]:
arr.reshape(10,5) #10*5 =50

array([[96, 32, 70, 70, 78],
       [ 5, 19, 89, 38, 21],
       [20, 56, 93, 49, 89],
       [28, 62, 78, 56, 17],
       [52, 90, 73, 34, 36],
       [42,  1, 12, 61, 36],
       [54, 99, 62, 25, 77],
       [28, 27, 50, 73, 87],
       [59,  5, 61, 28, 98],
       [66, 28, 25, 80, 97]])

In [32]:
arr.reshape(10,4)

ValueError: cannot reshape array of size 50 into shape (10,4)

# functions

In [34]:
print(arr.max())
arr.min()

99


1

In [38]:
#find index of max or min
print('Index of max :',arr.argmax(),arr[arr.argmax()])
print('Index of min :',arr.argmin(),arr[arr.argmin()])

Index of max : 31 99
Index of min : 26 1


In [40]:
# find the shape
arr.shape

(50,)

In [41]:
arr.dtype

dtype('int64')