In [1]:
import numpy as np

In [3]:
ar = np.arange(0,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
#slicing
ar[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
ar[:5]

array([0, 1, 2, 3, 4])

In [9]:
#broadcast assignment
ar[:5] =0
ar

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
ar2 = ar
ar2[15:] =222 # update values in ar2 and ar as ar2 is reference to ar
ar

array([  0,   0,   0,   0,   0,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14, 222, 222, 222, 222, 222])

In [11]:
# to avaoid we can use copy
ar =np.arange(0,11)
ar2 = ar.copy()
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
ar2[:]=55
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
ar2

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

# 2D array

In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr[0][0]

1

In [17]:
arr[0]

array([1, 2, 3, 4])

In [19]:
arr[0,0] #singlw bracket notation

1

In [20]:
arr[:2,:2]

array([[1, 2],
       [5, 6]])

In [23]:
arr[1:4,2:]

array([[ 7,  8],
       [11, 12]])

# Array Operations

In [25]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arr+arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [27]:
arr*arr

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [28]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
arr/arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr**arr

array([[            1,             4,            27,           256],
       [         3125,         46656,        823543,      16777216],
       [    387420489,   10000000000,  285311670611, 8916100448256]])

In [31]:
arr * 10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [32]:
arr +100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [33]:
1/0

ZeroDivisionError: division by zero

In [34]:
arr/0

/home/sudhanshu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [36]:
np.array([0])/0

/home/sudhanshu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan])

In [37]:
np.exp(arr) #e**

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [38]:
np.max(arr)

12

In [39]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])